### ISSUE TITLE
Not working on KODI 19: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

### ISSUE THREAD

**Issue by Kugelfang666** [bobo1on1/script.xbmc.boblight#49]
Just updated from Kodi 18 (32bit) to 19 (64bit) on my windows machine. Kadi is working but the bob light add-on does not start. In the Log I found these errors. There seem to be others with the identical issue. 

https://forum.kodi.tv/showthread.php?tid=116331&page=106

```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: can't concat str to bytes
                                                   Traceback (most recent call last):
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\script.xbmc.boblight\default.py", line 242, in <module>
                                                       run_boblight()
                                                     File "C:\Users\ XXXXX\AppData\Roaming\Kodi\addons\script.xbmc.boblight\default.py", line 193, in run_boblight
                                                       if main.startup() == 0:
                                                     File "C:\Users\ XXXXX\AppData\Roaming\Kodi\addons\script.xbmc.boblight\default.py", line 130, in startup
                                                       if xbmcgui.Dialog().yesno(__scriptname__, localize(32504) + " " + localize(32509)):
                                                   TypeError: can't concat str to bytes
                                                   -->End of Python script error report<--
```

**Comment by playzino** [comment]
Same problem on 32bit and 64bit win :(

**Comment by kresimirvlahinic** [comment]
Same as above!

**Comment by rstock147** [comment]
exactly the same problem :-(

**Comment by lielle1** [comment]
same

**Comment by Reart0** [comment]
Is an update or fix planed?
Problem exists till now.
Are there alternatives?

**Comment by eadmaster** [comment]
> Are there alternatives?

yes:
https://github.com/hyperion-project/hyperion.kodi/issues/45
